source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.5'

target 'Rapid' do
  use_frameworks!

  pod 'GoogleWebRTC'
  pod 'GoogleMLKit/ObjectDetection', '9.0.0' 

  target 'RapidTests' do
    inherit! :search_paths
  end

  target 'RapidUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # ここは必要ならそのまま
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      # ★ EXCLUDED_ARCHS は削除
    end
  end

  # メインプロジェクトにも設定を適用（EXCLUDED_ARCHS は削除）
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        # ここにも EXCLUDED_ARCHS は設定しない
      end
    end
  end
end
